services:
  backend:
    image: ${DOCKER_USERNAME}/eshop:latest
    platform: linux/arm64  # Changed from linux/amd64
    ports:
      - "8080:8080"
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
      - "6004:6004"
      - "6005:6005"
      - "6006:6006"
      - "6007:6007"
      - "6008:6008"
      - "6009:6009"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_DATABASE_URI}
      - JWT_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - IMAGEKIT_PUBLIC_KEY=${IMAGEKIT_PUBLIC_KEY}
      - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_SECRET_KEY}
      - IMAGEKIT_URL_ENDPOINT=${IMAGEKIT_URL_ENDPOINT:-https://ik.imagekit.io/your_imagekit_id}
      - KAFKA_BROKER_URL=${KAFKA_BROKER_URL:-kafka://localhost:9092}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - NODE_OPTIONS=--max-old-space-size=2048  # Reduced from 4096
    env_file:
      - .env
    command: sh -c "npx nx run-many --target=build --projects=auth-service,product-service,order-service,seller-service,admin-service,api-gateway,kafka-service,logger-service,chatting-service,recommendation-service && npx nx run-many --target=serve --projects=auth-service,product-service,order-service,seller-service,admin-service,api-gateway,kafka-service,logger-service,chatting-service,recommendation-service"
    deploy:
      resources:
        limits:
          memory: 3G  # Reduced from 6G
          cpus: '2.0'

  user-ui:
    image: ${DOCKER_USERNAME}/eshop:latest
    platform: linux/arm64  # Added ARM64 support
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=1024  # Reduced from 4096
      - PORT=3000
      - NEXT_PUBLIC_SERVER_URI=${NEXT_PUBLIC_SERVER_URI:-http://localhost:8080}
      - NEXT_PUBLIC_SELLER_SERVER_URI=${NEXT_PUBLIC_SELLER_SERVER_URI:-http://localhost:3001}
      - NEXT_PUBLIC_CHATTING_WEBSOCKET_URI=${NEXT_PUBLIC_CHATTING_WEBSOCKET_URI:-ws://localhost:6006}
      - NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${NEXT_PUBLIC_STRIPE_PUBLIC_KEY}
    env_file:
      - apps/user-ui/.env
    command: sh -c "PORT=3000 npm run user-ui"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.0'

  seller-ui:
    image: ${DOCKER_USERNAME}/eshop:latest
    platform: linux/arm64  # Added ARM64 support
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=1024  # Reduced from 4096
      - PORT=3001
      - NEXT_PUBLIC_SERVER_URI=${NEXT_PUBLIC_SERVER_URI:-http://localhost:8080}
      - NEXT_PUBLIC_USER_UI_LINK=${NEXT_PUBLIC_USER_UI_LINK:-http://localhost:3000}
      - NEXT_PUBLIC_CHATTING_WEBSOCKET_URI=${NEXT_PUBLIC_CHATTING_WEBSOCKET_URI:-ws://localhost:6006}
    env_file:
      - apps/seller-ui/.env
    command: sh -c "PORT=3001 npm run seller-ui"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.0'

  admin-ui:
    image: ${DOCKER_USERNAME}/eshop:latest
    platform: linux/arm64  # Added ARM64 support
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=1024  # Reduced from 4096
      - PORT=3002
      - NEXT_PUBLIC_SERVER_URI=${NEXT_PUBLIC_SERVER_URI:-http://localhost:8080}
      - NEXT_PUBLIC_USER_UI_LINK=${NEXT_PUBLIC_USER_UI_LINK:-http://localhost:3000}
      - NEXT_PUBLIC_SOCKET_URI=${NEXT_PUBLIC_SOCKET_URI:-ws://localhost:6008}
    env_file:
      - apps/admin-ui/.env
    command: sh -c "PORT=3002 npm run admin-ui"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.0'
