services:
  backend:
    image: ${DOCKER_USERNAME}/eshop:latest
    ports:
      - "8080:8080"
      - "6001:6001"
      - "6002:6002"
      - "6003:6003"
      - "6004:6004"
      - "6005:6005"
      - "6006:6006"
      - "6007:6007"
      - "6008:6008"
      - "6009:6009"
    environment:
      # These will be provided at RUNTIME, not build time
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - IMAGEKIT_PUBLIC_KEY=${IMAGEKIT_PUBLIC_KEY}
      - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
      - IMAGEKIT_URL_ENDPOINT=${IMAGEKIT_URL_ENDPOINT}
      - KAFKA_BROKER_URL=${KAFKA_BROKER_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    # Use local .env file (gitignored)
    env_file:
      - .env
    command: npm run dev

  user-ui:
    image: ${DOCKER_USERNAME}/eshop:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SERVER_URI=${NEXT_PUBLIC_SERVER_URI:-http://localhost:8080}
      - NEXT_PUBLIC_SELLER_SERVER_URI=${NEXT_PUBLIC_SELLER_SERVER_URI:-http://localhost:3001}
      - NEXT_PUBLIC_CHATTING_WEBSOCKET_URI=${NEXT_PUBLIC_CHATTING_WEBSOCKET_URI:-ws://localhost:6006}
      - NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${NEXT_PUBLIC_STRIPE_PUBLIC_KEY}
    env_file:
      - apps/user-ui/.env
    command: npm run user-ui

  seller-ui:
    image: ${DOCKER_USERNAME}/eshop:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SERVER_URI=${NEXT_PUBLIC_SERVER_URI:-http://localhost:8080}
      - NEXT_PUBLIC_USER_UI_LINK=${NEXT_PUBLIC_USER_UI_LINK:-http://localhost:3000}
      - NEXT_PUBLIC_CHATTING_WEBSOCKET_URI=${NEXT_PUBLIC_CHATTING_WEBSOCKET_URI:-ws://localhost:6006}
    env_file:
      - apps/seller-ui/.env
    command: npm run seller-ui

  admin-ui:
    image: ${DOCKER_USERNAME}/eshop:latest
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SERVER_URI=${NEXT_PUBLIC_SERVER_URI:-http://localhost:8080}
      - NEXT_PUBLIC_USER_UI_LINK=${NEXT_PUBLIC_USER_UI_LINK:-http://localhost:3000}
      - NEXT_PUBLIC_SOCKET_URI=${NEXT_PUBLIC_SOCKET_URI:-ws://localhost:6008}
    env_file:
      - apps/admin-ui/.env
    command: npm run admin-ui
